services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  ingest:
    build:
      context: .
      dockerfile: ingest/Dockerfile
    env_file:
      - .env
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
  eval:
    build:
      context: .
      dockerfile: eval/Dockerfile
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
    volumes:
      - ./eval/results:/results
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
      ingest:
        condition: service_completed_successfully
      api:
        condition: service_started

  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
